apiVersion: apps/v1
kind: Deployment
metadata:
  name: FinalCaseProject
spec:
  selector:
    matchLabels:
      app: FinalCaseProject
  replicas: 1
  template:
    metadata:
      labels:
        app: FinalCaseProject
    spec:
      containers:
        - name: finalcaseproject
          image: hashus12/finalcaseproject:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 1Gi
            limits:
              cpu: 1
              memory: 1Gi